import { CirclePlus } from "lucide-react";

export const UserModelFormConfig = {
    moduleTitle: "Manage Users",
    title: "Add New Users",
    description: "Fill in the details below to add a new user",

    // THIS FOR BUTTON IN THE TOP OF TABLE
    addButton: {
        id: "add-user",
        label: "Add New User",
        className:
            "bg-sidebar shadow-lg text-white rounded-sm px-4 py-2 hover:bg-sidebar hover:shadow-xl cursor-pointer",
        icon: CirclePlus,
        type: "button" as const,
        variant: "default" as const,
    },
    // FORM FIELDS
    fields: [
        {
            id: "name",
            key: "formUsername",
            name: "name",
            label: "",
            type: "text" as const,
            placeholder: "Enter user name",
            tabindex: 1,
            autoFocus: true,
            className: "",
        },
        {
            id: "email",
            key: "formEmail",
            name: "email",
            label: "",
            type: "text" as const,
            placeholder: "",
            tabindex: 2,
            className: "",
        },
        {
            id: "password",
            key: "formPassword",
            name: "password",
            label: "",
            type: "password" as const,
            placeholder: "",
            tabindex: 3,
            className: "",
        },
        {
            id: "confirm_password",
            key: "formConfirmPassword",
            name: "confirm_password",
            label: "",
            type: "password" as const,
            placeholder: "",
            tabindex: 4,
            className: "",
        },
        {
            id: "mobile_number",
            key: "formMobile",
            name: "mobile_number",
            label: "",
            type: "tel" as const,
            placeholder: "Enter Mobile Number 05XXXXXXXX",
            tabindex: 5,
            className: "",
        },
        {
            id: "department",
            key: "formDepartment",
            name: "department",
            label: "",
            type: "select" as const,
            placeholder: "",
            tabindex: 6,
            className: "",
        },
        {
            id: "designation",
            key: "formDesignation",
            name: "designation",
            label: "",
            type: "select" as const,
            placeholder: "",
            tabindex: 7,
            className: "",
        },
        {
            id: "role",
            key: "formRole",
            name: "role",
            label: "",
            type: "select" as const,
            placeholder: "",
            tabindex: 8,
            className: "",
        },
    ],
    // FORM BUTTONS
    buttons: [
        {
            key: "cancel",
            type: "button" as const,
            label: "Cancel",
            variant: "destructive" as const,
            className: "cursor-pointer",
        },
        {
            key: "submit",
            type: "submit" as const,
            label: "Save Changes",
            variant: "default" as const,
            className: "cursor-pointer",
        },
    ],
};
